In [1]:
import numpy as np


# Para cada una de las expresiones que figuran a continuación, especifique su tipo y valor.
### Diga si genera un error o no puedeespecificar el tipo.

Supongamos que hemos hecho la siguiente asignación:

x = (1, 2, (3, 'Juan', 4), 'Hola')

x[0]          El resultado es 1

x[2]          El resultado es (3, 'Juan', 4)

x[-1]         El resultado es 'Hola'

x[2][2]       4

x[2][-1]      4

x[-1][-1]     'a'

x[-1][2]      'l'

x[0:1]        1

x[0:-1]       (1, 2, (3, 'Juan', 4) 

len(x)        4

2 in x        True

3 in x        False

x[0] = 8      Error

In [1]:
x = (1, 2, (3, 'Juan', 4), 'Hola')

In [2]:
x[0]

1

In [3]:
x[2]

(3, 'Juan', 4)

In [4]:
x[-1]

'Hola'

In [5]:
x[2][2]

4

In [6]:
x[2][-1]

4

In [7]:
x[-1][-1]

'a'

In [8]:
x[-1][2]

'l'

In [9]:
x[0:1]

(1,)

In [10]:
x[0:-1]

(1, 2, (3, 'Juan', 4))

In [11]:
len(x)

4

In [12]:
2 in x

True

In [13]:
3 in x

False

In [14]:
x[0] = 8

TypeError: 'tuple' object does not support item assignment

## Para cada una de las expresiones que figuran a continuación, especifique su tipo y valor. Diga si genera un error o si no puede especificar su tipo.

Supongamos que hemos hecho la siguiente asignación:

x = [1, 2, [3, 'Juan', 4], 'Hola']

x[0]          El resultado es 1

x[2]          El resultado es (3, 'Juan', 4)

x[-1]         El resultado es 'Hola'

x[2][2]       El resultado es 4

x[2][-1]      El resultado es 4

x[-1][-1]     El resultado es 'a'

x[-1][2]      El resultado es 'l'

x[0:1]        El resultado es 1

x[0:-1]       El resultado es [1, 2, [3, 'Juan', 4] 

len(x)        El resultado es 4

2 in x        El resultado es True

3 in x        El resultado es False

x[0] = 8      No da error

In [16]:
x = [1, 2, [3, 'Juan', 4], 'Hola']

In [17]:
x[0]

1

In [18]:
x[2]

[3, 'Juan', 4]

In [19]:
x[-1]

'Hola'

In [20]:
x[2][2]

4

In [21]:
x[2][-1]

4

In [22]:
x[-1][-1]

'a'

In [23]:
x[-1][2]

'l'

In [24]:
x[0:1]

[1]

In [25]:
x[0:-1]

[1, 2, [3, 'Juan', 4]]

In [26]:
len(x)

4

In [27]:
2 in x 

True

In [28]:
3 in x

False

In [29]:
x[0] = 8

In [2]:
arreglo = np.arange(9)
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
Mat1 = np.array([[1,1],[1,1]])
Mat2 = np.array([[2,2],[2,2]])

In [7]:
suma = Mat1 + Mat2
print(suma)

[[3 3]
 [3 3]]


In [8]:
multi = Mat1.dot(Mat2)
print(multi)

[[4 4]
 [4 4]]


In [9]:
n=int(raw_input("Renglones: "))
print(n)
m =int(raw_input("Columnas "))
print(m)

matriz = np.arange(n*m).reshape(n,m)

for i in range(n):
    for j in range(m):
        print("Introduzca el elemento ",i,j)
        matriz[i][j]=raw_input()
        
print(matriz)

Renglones: 3
3
Columnas 3
3
('Introduzca el elemento ', 0, 0)
1
('Introduzca el elemento ', 0, 1)
2
('Introduzca el elemento ', 0, 2)
3
('Introduzca el elemento ', 1, 0)
4
('Introduzca el elemento ', 1, 1)
5
('Introduzca el elemento ', 1, 2)
6
('Introduzca el elemento ', 2, 0)
7
('Introduzca el elemento ', 2, 1)
8
('Introduzca el elemento ', 2, 2)
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
